### ISSUE TITLE
robot acts instantly

### ISSUE THREAD

**Issue by Desour** [ac-minetest/basic_robot#3]
everything is done at once, the robot only takes time after everything is done
it would be nice if it takes time between each command, the player could follow the happenings

**Comment by ac-minetest** [comment]
You can achieve that by programming the robot using states:
example walking and turning:

if state = turning then turn around state = walk exit
if state= walking then try walk, if you cant then go state turning exit

**Comment by Desour** [comment]
the problem is that its really cheaty if the player can make the robot be so fast

**Comment by Desour** [comment]
I have my samer now that does this, basic_robot is different.
