### ISSUE TITLE
String gets broken

### ISSUE THREAD

**Issue by raymoo** [ac-minetest/basic_robot#4]
The following program is broken; it broadcasts the wrong message:

```
say("while dogs are cute, cats are also cute")
```

Instead of the intended message, it prints "while do increase_counter(); gs are cute, cats are also cute"

**Comment by hajo4** [comment]
Same here [Test3-lookout](http://wiki.minetest.net/Mods/basic_robot#Test3_-_lookout) with
say("done.")

**Comment by ac-minetest** [comment]
fixed
