### ISSUE TITLE
Broken string

### ISSUE THREAD

**Issue by raymoo** [ac-minetest/basic_robot#8]
The following program outputs the wrong output:
```
say("\"while do gs are cute, cats are also cute\"")
```
The incorrect output is
"\"while do increase_counter(); gs are cute, cats are also cute\""

**Comment by ac-minetest** [comment]
don't make grammar errors, correct is "dogs"  not "do gs" :)
note: this only changes displayed string as described.

**Comment by raymoo** [comment]
Is it fixed?
